### ISSUE TITLE
Incorrect path while running mcts_agent_training.sh

### ISSUE THREAD

**Issue by sun123-cmd** [NYU-MLDA/ABC-RL#1]
Thanks for your nice wok!

I set BENCHMARK_DIR in both `main.py` as `/home/sun/Desktop/ABC-RL/arithmetic` ;
I set HOME_DIR in `mcts_agent_training.sh` as `/home/sun/Desktop/ABC-RL`

 While runing `mcts_agent_training.sh`, log file shows:
 ```shell
1 /home/sun/miniconda3/envs/abcrl/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
2   warnings.warn(
3 /home/sun/miniconda3/envs/abcrl/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
4   warnings.warn(
5 Incorrect path. Rerun
```
I wonder which path may be incorrect and how to solve this issue.
Thanks and best wishes!

**Comment by sun123-cmd** [comment]
I tried to only run `python main.py --ttsplit 5001 --library /home/sun/Desktop/ABC-RL/lib/7nm/7nm.lib --dumpdir /home/sun/Desktop/ABC-RL/ABC-RL_ICLR/dump --runID 15001`directly at the path of ICLR/src, failed same as follows:
```
/home/sun/miniconda3/envs/abcrl/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/sun/miniconda3/envs/abcrl/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Incorrect path. Rerun
```

**Comment by animeshbchowdhury** [comment]
Can you modify the following in mcts_agent_training.sh?

`--library ${HOME_DIR}/ABC_RL_ICLR/lib/7nm/7nm.lib`. This should resolve it.

**Comment by sun123-cmd** [comment]
> Can you modify the following in mcts_agent_training.sh?
> 
> `--library ${HOME_DIR}/ABC_RL_ICLR/lib/7nm/7nm.lib`. This should resolve it.

Thanks for your replay! 
I tried as your method but failed same as the past. 
It seems that under ${HOME_DIR}/ABC_RL_ICLR path doesn 't have /lib/7nm/7nm.lib file, just containing /dump and /src

**Comment by animeshbchowdhury** [comment]
Can you retry now with the original traning.sh script? The .gitignore didn't allow to push the library file so it was missed during commit. I've added it now. Please check.

**Comment by sun123-cmd** [comment]
> Can you retry now with the original traning.sh script? The .gitignore didn't allow to push the library file so it was missed during commit. I've added it now. Please check.

Hello!
Thanks for your replay! I solved the path error as your advice. However, while running mcts_agent_training,sh script, I met following error:
```
 85 Traceback (most recent call last):
 86   File "/home/sun/Desktop/ABC-RL/ABC-RL_ICLR/src/main.py", line 266, in <module>
 87     r = Parallel(n_jobs=5,verbose=10)(delayed(collect_experiences)(trainer,idx) for idx in range(len(destRootAIGPaths[0]))    )
 88   File "/home/sun/miniconda3/envs/abcrl/lib/python3.9/site-packages/joblib/parallel.py", line 2007, in __call__
 89     return output if self.return_generator else list(output)
 90   File "/home/sun/miniconda3/envs/abcrl/lib/python3.9/site-packages/joblib/parallel.py", line 1650, in _get_outputs
 91     yield from self._retrieve()
 92   File "/home/sun/miniconda3/envs/abcrl/lib/python3.9/site-packages/joblib/parallel.py", line 1754, in _retrieve
 93     self._raise_error_fast()
 94   File "/home/sun/miniconda3/envs/abcrl/lib/python3.9/site-packages/joblib/parallel.py", line 1789, in _raise_error_fast
 95     error_job.get_result(self.timeout)
 96   File "/home/sun/miniconda3/envs/abcrl/lib/python3.9/site-packages/joblib/parallel.py", line 745, in get_result
 97     return self._return_or_raise()
 98   File "/home/sun/miniconda3/envs/abcrl/lib/python3.9/site-packages/joblib/parallel.py", line 763, in _return_or_raise
 99     raise self._result
100 AttributeError: 'abc_py.AbcInterface' object has no attribute 'write'
```
I wonder whether this error is caused by my abc_py  install or our source codes? In abc_py repo, it seems that no one has met this issue~

**Comment by animeshbchowdhury** [comment]
I added the functionality in my abc_py. Can you use this meanwhile?

abc_rl_dependency: https://drive.google.com/file/d/16DlMYZqBHb07Wi0p9sGES-MW3yyMOJvz/view?usp=drive_link

I need to push this code into the repository and clean it up. Thanks for your patience.

**Comment by sun123-cmd** [comment]
> I added the functionality in my abc_py. Can you use this meanwhile?
> 
> abc_rl_dependency: https://drive.google.com/file/d/16DlMYZqBHb07Wi0p9sGES-MW3yyMOJvz/view?usp=drive_link
> 
> I need to push this code into the repository and clean it up. Thanks for your patience.

Hello~

I' m trying your abc_rl_dependency, directly unizp it and rebuild abc_py with your CMakelists.
Hower, while importing abc_py lib, another error occurs:
```python
Python 3.9.0 (default, Nov 15 2020, 14:28:56) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import abc_py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/hs/disk1/miniconda3/envs/abcrl/lib/python3.9/site-packages/abc_py.cpython-39-x86_64-linux-gnu.so: undefined symbol: Abc_FrameGetGlobalFrame
```
The version of my Linux kernel is `5.4.0-181-generic` , Ubuntu 20.04. 
I think maybe the error is caused by my OS or abc_py lib?

**Comment by sun123-cmd** [comment]
> I added the functionality in my abc_py. Can you use this meanwhile?
> 
> abc_rl_dependency: https://drive.google.com/file/d/16DlMYZqBHb07Wi0p9sGES-MW3yyMOJvz/view?usp=drive_link
> 
> I need to push this code into the repository and clean it up. Thanks for your patience.

Thank you! I can run `mcts_agent_training.sh` with your new dependency!
Here is my conda env, hopes I can help other developers run your code:
**https://drive.google.com/file/d/1eleYv19AmxE5-WRhlFjsvAGvTHRyq96j/view?usp=drive_link**

**Comment by animeshbchowdhury** [comment]
Thanks @sun123-cmd. Appreciate this.
